# Generated by Django 3.1.1 on 2020-09-21 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200921_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
